# Generated by Django 5.2.7 on 2025-10-11 06:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DifferentPackets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='packets/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('TED', 'TEDAMEDA'), ('BI', 'BINGO RED'), ('LE', 'LEGE RED'), ('PO', 'POTATO GREEN'), ('MI', 'MIXTURE')], max_length=3)),
            ],
        ),
    ]
