# Generated by Django 5.2.7 on 2025-10-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='differentpackets',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
