# Generated by Django 5.2.7 on 2025-10-13 17:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packet', '0002_differentpackets_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PacketProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_proof', models.CharField(max_length=100)),
                ('issued_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField()),
                ('pack', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='packet.differentpackets')),
            ],
        ),
        migrations.CreateModel(
            name='PacketReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[('1', 'Bad'), ('2', 'ok'), ('3', 'Normal'), ('4', 'Good'), ('5', 'Very Good')])),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField()),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='packet.differentpackets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('diff_packet', models.ManyToManyField(related_name='stores', to='packet.differentpackets')),
            ],
        ),
    ]
