# Generated by Django 5.2.7 on 2025-10-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packet', '0003_packetproof_packetreview_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packetreview',
            name='rating',
            field=models.IntegerField(choices=[('1', 'Bad'), ('2', 'ok'), ('3', 'Normal'), ('4', 'Good'), ('5', 'Very Good')], max_length=2),
        ),
    ]
